# permissions for end users to edit persistentvolumesnapshots.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: persistentvolumesnapshot-editor-role
rules:
- apiGroups:
  - storage.u2386.github.com
  resources:
  - persistentvolumesnapshots
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.u2386.github.com
  resources:
  - persistentvolumesnapshots/status
  verbs:
  - get
